baseURL = "https://outsourcedselling.com/"
title = "Outsourced Sales"

languageCode = "en-us"
DefaultContentLanguage = "en"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 9
darkmode_js = ["assets/js/darkmode.js"]
enableInlineShortcodes = true

[params]
author = "iMobilize Ltd"
authorimage = "../assets/images/global/author.webp"
github = "https://github.com/imobilize"
facebook = "https://facebook.com/outsourcedsales"
og_image = "/images/tailbliss-cover.png"
sitename = "Outsourced Selling"
twitter = "@outsourcedsales"
description = "Outsourced sales is an agency which handles your sales pipeline for you"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "Categories"
tag = "Tags"

[privacy]
[privacy.disqus]
disable = false
[privacy.googleAnalytics]
anonymizeIP = true
disable = false
respectDoNotTrack = false
useSessionStorage = false
[privacy.instagram]
disable = false
simple = false
[privacy.twitter]
disable = false
enableDNT = false
simple = false
[privacy.vimeo]
disable = false
enableDNT = false
simple = false
[privacy.youtube]
disable = false
privacyEnhanced = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.104.0"
